// <auto-generated />
namespace WEBPOS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserMobileProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMobileProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201905210043175_UserMobileProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
